---
- hosts: all
  become: yes
  tasks:
   - name: APT - install misc packages
     apt:
       name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'gnupg-agent']
       update_cache: yes
   - name: Apt - add signing key, uses URL
     apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present
   - name: Verifying the key with the fingerprint
     command: apt-key fingerprint 0EBFCD88
     register: fingerprint_check
     changed_when: False
     failed_when: "'9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88' not in fingerprint_check.stdout"
   - name: APT - add Docker repository
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      state: present
   - name: Install Docker packages
     apt:
      name: ['docker-ce','docker-ce-cli','containerd.io']
      update_cache: yes
      state: present
     notify:
        - restart docker
   - name: add users to docker group
     user:
      name: ubuntu
      groups: docker
      append: yes
   - name: Execute nginx
     shell: docker run -d -p 8080 nginx
  handlers:
      - name: restart docker
        service:
         name: docker_service
         state: restarted
